version: '3.7'
services:
  redis:
    image: redis:latest
    ports:
      - ${REDIS_SERVER_PORT}:${REDIS_SERVER_PORT}
    environment:
      - REDIS_PORT=${REDIS_SERVER_PORT}
      - REDIS_DATABASES=${REDIS_DATABASES}
      - REDIS_TIMEOUT=${REDIS_TIMEOUT}
    restart: always

  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${POSTGRESQL_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRESQL_PASSWORD}
    volumes:
      - D:\postgres_datapart:/var/lib/postgresql/data
    ports:
      - ${POSTGRESQL_SERVER_PORT}:${POSTGRESQL_SERVER_PORT}