spring:
  application:
    name: AnonymChatBot
  data:
    redis:
      host: redis
      port: ${REDIS_PORT}
      timeout: ${REDIS_TIMEOUT}

telegram:
  bot:
    name: ${TELEGRAM_BOT_NAME}
    token: ${TELEGRAM_BOT_TOKEN}

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true

server:
  port: ${SERVER_PORT}