spring:
  application:
    name: AnonymChatBot
  data:
    redis:
      host: redis
      port: ${REDIS_PORT}
      timeout: ${REDIS_TIMEOUT}

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgres:${POSTGRESQL_SERVER_PORT}/${POSTGRESQL_DATABASE_NAME}
    username: ${POSTGRESQL_USERNAME}
    password: ${POSTGRESQL_PASSWORD}

  jpa:
    database: postgresql
    show-sql: true

  liquibase:
    change-log: db/changelog/main/main-changelog.yml

telegram:
  bot:
    name: ${TELEGRAM_BOT_NAME}
    token: ${TELEGRAM_BOT_TOKEN}

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true

server:
  port: ${SERVER_PORT}